name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'
          check-latest: true

      - name: Tidy modules
        run: go mod tidy

      - name: Format check
        run: |
          fmtout=$(gofmt -l .)
          if [ -n "$fmtout" ]; then
            echo "Go files not formatted:" && echo "$fmtout"
            exit 1
          fi

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build ./...

      - name: Test
        run: go test ./... -v

